name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout repository
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build img
        run: sudo docker build . --file Dockerfile --tag marc-stables/mpostest:123
      - name: Push img
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          sudo docker push marc-stables/mpostest:123
